### ISSUE TITLE
Attempt to call private templating service

### ISSUE THREAD

**Issue by daum** [APY/APYDataGridBundle#1030]
In https://github.com/APY/APYDataGridBundle/blob/master/Grid/Grid.php#L2150 it seems the grid calls the templating service directly which isn't public so it isn't possible.  I'm on 4.2 but I know people are using this on 3.4+ which the services are private so wanted to check before I dug too deep to make sure I am not missing something.

**Comment by daum** [comment]
Ah it was related to not having in my framework.yaml:
```
framework:
    templating:
        engines:
          - twig
```
