### ISSUE TITLE
Translation with Knp\DoctrineBehaviors

### ISSUE THREAD

**Issue by flopp26** [APY/APYDataGridBundle#661]
Salut, je profite que l'auteur de ce bundle soit français pour demander de l'aide en français. 

Pour la traduction je n'utilise pas gedmo mais Knp\DoctrineBehaviors et je n'arrive pas à récupérer l'information de mon champ traduit.

Pour info j'utilise ce repo "https://github.com/acseo/APYDataGridBundle.git" pour avoir l'annotation par fichier yml (trouvé sur un tuto de l'afsy)

bref j'ai une entité Ticket mappé sur Subject qui elle meme est mappé sur subjectTranslations

``` php
class Ticket
{

    /**
     * @var Subject
     * @ORM\ManyToOne(targetEntity="Acme\HelpDeskBundle\Entity\Subject", inversedBy="tickets")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotNull(message="form.contact.constraints.subject.notnull")
     */
    protected $subject;
}

use Knp\DoctrineBehaviors\Model\Translatable\Translatable;

/**
 * @ORM\Entity(repositoryClass="Acme\HelpDeskBundle\Repository\SubjectRepository")
 * @ORM\Table(name="ticket_subject")
 */
class Subject
{
    use Translatable;
}

use Knp\DoctrineBehaviors\Model\Translatable\Translation;

/**
 * @ORM\Entity()
 * @ORM\Table(name="ticket_subject_translations")
 */
class SubjectTranslation
{
    use Translation;

/**
     * @ORM\Column(name="title", type="text")
     */
    protected $title;
}
```

Et j'utilise ceci dans la configuration de la grille

``` yml
Acmel\HelpDeskBundle\Entity\Ticket:
    Source:
        columns:
            subject.translations.title: ~          
        groupBy: ~
        filterable: ~
    Columns:        
        subject.translations.title:
            filterable: true
            filter: select
            operatorsVisible: false
            visible: true
            id: subject
            title: sujet
            field: subject.translations.title
            source: true        
```

J'arrive bien à avoir mon titre de sujet, mais comme à aucun endroit la local est spécifié j'ai chaque sujet qui est multiplié par le nombre de langue. je ne comprends comment faire pour spécifier la jointure sur la locale.

merci d'avance pour ton aide
