### ISSUE TITLE
Bug ? setRouteParametersMapping

### ISSUE THREAD

**Issue by flopp26** [APY/APYDataGridBundle#665]
Hi I want to generate route in row action and I have made this:

``` yml
admin_helpdesk_ticket_comment:
    path: /helpdesk/ticket-add-comment/{ticket}
    defaults: { _controller: AcmeBundle:HelpDesk/HelpDeskAdmin:addComment }
    requirements:
        ticket: \d+
```

``` php
$rowActionView = new RowAction('Répondre', 'admin_helpdesk_ticket_comment');
$rowActionView->setRouteParameters(array('ticket'));
$rowActionView->setRouteParametersMapping(array('ticket' => 25)); // 25 doit corresponde à l'id de la ligne
```

But I get this error

```
An exception has been thrown during the rendering of a template ("Some mandatory parameters are missing ("ticket") to generate a URL for route "fr__RG__admin_helpdesk_ticket_comment".") 
```

Any idea ? I have try with exemple in doc, but same error :-(
