### ISSUE TITLE
Problem w Annotation OneToMany Relations

### ISSUE THREAD

**Issue by Canser** [APY/APYDataGridBundle#694]
Hello. I don't know is this a problem but i have to ask this.

I want to get the last record with onetomany relation.

`* @GRID\Column(title="Hareket", field="movements.last.group.name", filterable=false)`

Product: 
```
    oneToMany:
        movements:
          targetEntity: CS\OrderBundle\Entity\OrderMovement
          mappedBy: panoramic_order
          cascade: ["all"]
          fetch: EXTRA_LAZY
```

But it gives me an error.

>[Semantical Error] line 0, col 51 near 'last as movements::last,': Error: Class CS\OrderBundle\Entity\OrderMovement has no field or association named last

What should i do to get the last movement?
