### ISSUE TITLE
GroupConcat for manyToMany field - current way to do it

### ISSUE THREAD

**Issue by grekpg** [APY/APYDataGridBundle#850]
I need use grouping for ManyToMany - read here
https://github.com/APY/APYDataGridBundle/blob/master/Resources/doc/columns_configuration/annotations/dql_function.md 

but link https://github.com/beberlei/DoctrineExtensions/blob/master/lib/DoctrineExtensions/Query/Mysql/ is broken 

i have installed "stof/doctrine-extensions-bundle": "~1.1@dev", 

but it not help - when i use 

@GRID\Column(field="tags.title:GroupConcat",  title="tagi" ,filter="select",selectMulti="true")

i have error 

 Error: Expected known function, got 'GroupConcat'

How to setup it ?

**Comment by qferr** [comment]
Refer to https://github.com/beberlei/DoctrineExtensions/blob/master/src/Query/Mysql/GroupConcat.php

And you can register the function in `config.yml`:

```yml
doctrine:
    orm:
        dql:
            string_functions:
                group_concat:   DoctrineExtensions\Query\Mysql\GroupConcat
```
